const userProfiles = [
    {
      id: 1,
      name: 'John Doe',
      profilePicture: 'https://randomuser.me/api/portraits/men/1.jpg',
      email: 'john.doe@example.com',
      phone: '+1234567890',
      address: '123 Main St, Anytown, USA',
      age: 30,
      jobTitle: 'Software Engineer',
      bio: 'Passionate about technology and coding.',
    },
    {
      id: 2,
      name: 'Jane Smith',
      profilePicture: 'https://randomuser.me/api/portraits/women/2.jpg',
      email: 'jane.smith@example.com',
      phone: '+0987654321',
      address: '456 Elm St, Anytown, USA',
      age: 28,
      jobTitle: 'Product Manager',
      bio: 'Loves building products that users love.',
    },
    {
      id: 3,
      name: 'Alice Johnson',
      profilePicture: 'https://randomuser.me/api/portraits/women/3.jpg',
      email: 'alice.johnson@example.com',
      phone: '+1122334455',
      address: '789 Oak St, Anytown, USA',
      age: 25,
      jobTitle: 'UX Designer',
      bio: 'Designing intuitive user experiences.',
    },
    {
      id: 4,
      name: 'Bob Brown',
      profilePicture: 'https://randomuser.me/api/portraits/men/4.jpg',
      email: 'bob.brown@example.com',
      phone: '+2233445566',
      address: '101 Pine St, Anytown, USA',
      age: 35,
      jobTitle: 'DevOps Engineer',
      bio: 'Ensuring smooth deployments and operations.',
    },
    {
      id: 5,
      name: 'Charlie Black',
      profilePicture: 'https://randomuser.me/api/portraits/men/5.jpg',
      email: 'charlie.black@example.com',
      phone: '+3344556677',
      address: '202 Birch St, Anytown, USA',
      age: 40,
      jobTitle: 'Data Scientist',
      bio: 'Turning data into actionable insights.',
    },
  ];
  
  export default userProfiles;
  